### ISSUE TITLE
Error on using `import.meta`

### ISSUE THREAD

**Issue by efureev** [liulinboyi/unplugin-vue-import-props#3]
"vite": "^3.2.3",
"rollup": "^3.3.0",

<img width="890" alt="Снимок экрана 2022-11-14 в 02 16 46" src="https://user-images.githubusercontent.com/5524684/201547337-326354a1-75e3-459f-9aed-72175f341463.png">

**Comment by liulinboyi** [comment]
Thanks for your feedback, I'll take a look😉

**Comment by liulinboyi** [comment]
> "vite": "^3.2.3", "rollup": "^3.3.0",
> 
> <img alt="Снимок экрана 2022-11-14 в 02 16 46" width="890" src="https://user-images.githubusercontent.com/5524684/201547337-326354a1-75e3-459f-9aed-72175f341463.png">

Thank you, this issue has been fixed in [v0.0.6](https://www.npmjs.com/package/unplugin-vue-import-props/v/0.0.6)😉.
