### ISSUE TITLE
It doesn't work for vite 4.0.0

### ISSUE THREAD

**Issue by velly** [liulinboyi/unplugin-vue-import-props#5]
[v0.0.7-beta.0] doesn't work for vite 4.0.0.
Rollback to ^0.0.5-beta.6 is OK

**Comment by liulinboyi** [comment]
> [v0.0.7-beta.0] doesn't work for vite 4.0.0. Rollback to ^0.0.5-beta.6 is OK

@velly Thanks for your feedback, I'll take a look😉. Recently got sick, infected with COVID-19, I recently will try to resolve this issue.

**Comment by liulinboyi** [comment]
@velly  Can you provide the Error info or a minimal reproduction,  thanks!

**Comment by liulinboyi** [comment]
ok the issues was fixed. You can use `0.0.7-beta.1` to resolve this issue.

**Comment by velly** [comment]
> `ta.1` to resolve this issue.

Thank you [liulinboyi](https://github.com/liulinboyi), and take care of yourself.
