### ISSUE TITLE
[peerDependencies] requires update?

### ISSUE THREAD

**Issue by FranciscoKloganB** [liulinboyi/unplugin-vue-import-props#6]
See screenshot:

![image](https://user-images.githubusercontent.com/25959244/222266960-103d0499-fccb-4bc7-b725-10f7b78a69b9.png)

From my understanding this seems to be working with Vite ^4.0.0, but peer dependencies complain. Should peer deps be relaxed on unplugin-vue-import-props?

**Comment by unitydynamics** [comment]
I'm also using Vite 4.0 so would be interested to see if it's compatible there...

**Comment by liulinboyi** [comment]
> See screenshot:
> 
> ![image](https://user-images.githubusercontent.com/25959244/222266960-103d0499-fccb-4bc7-b725-10f7b78a69b9.png)
> 
> From my understanding this seems to be working with Vite ^4.0.0, but peer dependencies complain. Should peer deps be relaxed on unplugin-vue-import-props?

ok, I will have a try.

**Comment by liulinboyi** [comment]
@unitydynamics @FranciscoKloganB The unplugin's version has been updated.
